[settings]
timeout = 1000

[relaychain]
command = "polkadot"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"

  [[relaychain.nodes]]
  name = "bob"

[[parachains]]
id = 1002
chain="contracts-rococo-dev"

  [parachains.collator]
  name = "contracts"
  command = "polkadot-parachain"
  ws_port = 9988
  args = ["-lparachain=debug"]
