[settings]
timeout = 1000

[relaychain]
command = "polkadot"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"

  [[relaychain.nodes]]
  name = "bob"

[[parachains]]
id = 1281
chain = "moonbase-local"

  [parachains.collator]
  name = "alith"
  command = "moonbeam"
  ws_port = 9988
  args = ["-lparachain=debug --force-authoring"]
